export default {
	Swipe: 'swipe',
	Pan: 'pan',
	Pinch: 'pinch',
	Press: 'press',
	Rotate: 'rotate',
	Tap: 'tap',
	// swipe: 'swipe',
	// swipeleft: 'swipe',
	// swiperight: 'swipe',
	// swipeup: 'swipe',
	// swipedown: 'swipe',
	// pan: 'pan',
	// panstart: 'pan',
	// panmove: 'pan',
	// panend: 'pan',
	// pancancel: 'pan',
	// panleft: 'pan',
	// panright: 'pan',
	// panup: 'pan',
	// pandown: 'pan',
	// pinch: 'pinch',
	// pinchstart: 'pinch',
	// pinchmove: 'pinch',
	// pinchend: 'pinch',
	// pinchcancel: 'pinch',
	// pinchin: 'pinch',
	// pinchout: 'pinch',
	// press: 'press',
	// pressup: 'press',
	// rotate: 'rotate',
	// rotatestart: 'rotate',
	// rotatemove: 'rotate',
	// rotateend: 'rotate',
	// rotatecancel: 'rotate',
	// tap: 'tap',
};
